---
name: "Discogs"
guid: "4ce89c27-d3a1-4e4b-8f5f-4bd9191c857e"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-discogs.png"
version: 3
targetAbi: "10.11.5.0"
framework: "net9.0"
overview: "Get music metadata from Discogs"
description: >
  Get music metadata from Discogs

category: "Music"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.Discogs.dll"
changelog: |-
  - Revert "Update dependency System.Threading.RateLimiting to v10" (#18) @Shadowghost

  ### Dependency updates ###
  - Update dependency System.Threading.RateLimiting to v10 (#11) @[renovate[bot]](https://github.com/apps/renovate)
