---
name: "Discogs"
guid: "4ce89c27-d3a1-4e4b-8f5f-4bd9191c857e"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-discogs.png"
version: 2
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Get music metadata from Discogs"
description: >
  Get music metadata from Discogs

category: "Music"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.Discogs.dll"
changelog: |-
  - Jellyfin 10.11 support (#15) @crobibero
