---
name: "Discogs"
guid: "4ce89c27-d3a1-4e4b-8f5f-4bd9191c857e"
version: "1.0.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Get music metadata from Discogs"
description: >
  Get music metadata from Discogs
category: "Metadata"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.Discogs.dll"
changelog: >
  - Initial release
